### ISSUE TITLE
AdvancedChat player display name issue

### ISSUE THREAD

**Issue by GuavaDealer** [AdvancedPlugins/Chat#281]
### Describe the bug

so far i have only tested it on the mention part of the config, using `%player_displayname%` does not work while `%player_name%` does

Broken Example:
```yaml
mention:
  enabled: true
  char: "@"
  replacement: "<dark_aqua>@%player_displayname%</dark_aqua>"
  sound:
    name: "entity.player.levelup"
    volume: 1
    pitch: 1
```

### How to reproduce

simply use the `%player_displayname%` placeholder in the mention part of the `config.yml` not sure about anywhere else since i haven't tried it elsewhere

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
You can use this placeholder expansion to fix it, however it will probably not work currently from my testing. I've suggested a fix to the author of the expansion. If he replies, it should be fixed in next update of that expansion

https://api.extendedclip.com/expansions/minimexpansion/

**Comment by GuavaDealer** [comment]
Alrighty, ty

**Comment by GuavaDealer** [comment]
I forgot to say that it just says in the message the name of the placeholder, i don't know if that changes anything

**Comment by GuavaDealer** [comment]
all placeholders should work here correct? if so, cmi display name placeholder doesnt work either

**Comment by GuavaDealer** [comment]
hey, i compiled your version of that papi extension and advancedchat is still not translating the placeholder

![Image](https://github.com/user-attachments/assets/0d6feb54-268c-4b67-8656-6965e5995971)

**Comment by ThomasWega** [comment]
Im not sure if you write it in chat if it'll get parsed

**Comment by GuavaDealer** [comment]
i did @GuavaDealer

**Comment by GuavaDealer** [comment]
i could fix it by disabling this feature and enabling cmi's chat mentioning (i'd need to give it a higher priority of course)
