### ISSUE TITLE
issues with [item]

### ISSUE THREAD

**Issue by Viivtor** [AdvancedPlugins/Chat#304]
### Describe the bug

Im using mini message gradients for some of my other plugins like harvester hoes and crates/pouches where the items getting displayed shows` </bold>` and dont make the text bold all the time.

`<bold> </bold>` the closing bold still shows under the item in chat

This seems to only be an issue with people that are not OP.
This happens only to items held by normal players

### How to reproduce

I just renamed a simple item `&5<bold>hello</bold>` and displayed it in chat both on an op´ed account and a default account.

On op account it showed the correct.
On default account it showed `&5hello</bold>`

### Screenshots / Videos

https://prnt.sc/3VoT8LattlVr

### Filled out form correct and using latest version

I Confirm

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting

**Comment by Viivtor** [comment]
Now its just posting all the lines directly in chat which makes it even worse!
Again it only does that for players and not myself that is OP.

Please fix asap :/

**Comment by Viivtor** [comment]
It did indeed remove the previous bug but now a new one popped up.

**Comment by ThomasWega** [comment]
Hey. Can you explain better what you mean by "its just posting all the lines directly in chat" please

**Comment by Viivtor** [comment]
Yeah so when players [item] it shows all the item lores in the chat as lines (without even hovering) it just posts the lores in the chat which is very spammy.

When i do though it works perfectly without anything weird happening. So fixed but not really fixed! xD

**Comment by Viivtor** [comment]
[https://imgur.com/lNDXcNZ](url)

**Comment by Viivtor** [comment]
https://imgur.com/lNDXcNZ

**Comment by ThomasWega** [comment]
Can you send a video please?

**Comment by Viivtor** [comment]
> Can you send a video please?
> […](#)

Theres not more other than in the photo i sent form imgur. Cant hover players messages with [item] it just floods the chat instead of being hover to see the item.

**Comment by ThomasWega** [comment]
I will need your full config as it seems with my default config it works fine. I think there needs to be a reset tag added somewhere. Either by you or by the code and that breaks the formatting

<img width="823" height="173" alt="Image" src="https://github.com/user-attachments/assets/5cb9e9a7-c06a-4f17-a632-01543686426e" />

**Comment by Viivtor** [comment]
It seems like this only happens to the Rivalharvesteerhoes item that has a very long lore. 10-20 lore lines. Other items seems to work perfectly now. I have default config in the [item] file.

**Comment by Viivtor** [comment]
Would also like to mention that it didnt set the lores in chat before, It started happening in the latest updates.

<img width="608" height="312" alt="Image" src="https://github.com/user-attachments/assets/441937f6-82ff-483c-bd13-5950632193f8" />

**Comment by ThomasWega** [comment]
Can you please try with all default config files?

**Comment by ThomasWega** [comment]
@Viivtor

**Comment by Viivtor** [comment]
> [@Viivtor](https://github.com/Viivtor)

I will try with default config as soon as I can and report back to you. Sorry for late response

**Comment by ThomasWega** [comment]
@Viivtor how's it looking?

**Comment by Hustle767** [comment]
Another issue when using apostrophe in named item for [item] hover chat shows up like this

<img width="739" height="146" alt="Image" src="https://github.com/user-attachments/assets/f3539996-7405-47f8-9111-7cdae5786cd8" />

**Comment by ThomasWega** [comment]
Should hopefully be fixed next update. Let me know when you get a chance to test it please

**Comment by ThomasWega** [comment]
Actually can anyone of you please create a ticket on the discord server and ping `@Wega` and I'll let you test first before release? I cannot replicate this myself so hard for me to test

**Comment by ThomasWega** [comment]
@Hustle767 
@Viivtor

**Comment by Hustle767** [comment]
> [@Hustle767](https://github.com/Hustle767) [@Viivtor](https://github.com/Viivtor)

I tested it and the issue still persist. I can narrow it down to it being an issue via op/permissions. When I try it with OP it works fine but when a regular player without OP permission tries it with the apostrophe it breaks.
